# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkWD7yGwMBxvKfzjcWr31iuXbZjCNHjf
"""

# Importar arquivo para o Colabory

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
       print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))

#Ler arquivo e inserir dados em uma matriz

arq = open(fn, 'r')  #abre o arquivo
texto = []  #declaro um vetor
matriz = [] #declaro um segundo vetor
texto = arq.readlines() #quebra as linhas do arquivo em vetores 

for i in range(len(texto)):          #esse for percorre a posições dp vetor texto
    matriz.append(texto[i].split())  #aqui quebra nos espasos das palavras

for i in range(len(texto)-7):          #mostra quedrando em linhas
      print(matriz[i+6])  

arq.close() #comando para fechar o arquivo

# Matriz de Distâncias
import math
import numpy

size = i + 1 # tamnho da matriz de distâncias
array = np.ones((size,size))# cria matriz do tamanho size x size 

x1 = 1 # coluna da coordenada x do primeiro ponto
y1 = 6 # linha da coordenada y do primeiro ponto
x2 = 1 # coluna da coordenada x do segundo ponto
y2 = 6 # linha da coordenada y do segundo ponto
linha = 0 # linha da array onde a distancia será armazenada
coluna = 0 # coluna da array onde a distancia será armazenada

for a in range (size):
    for j in range(size):
        xp1 = float(matriz[y1][x1])
        yp1 = float(matriz[y1] [x1 + 1])
        xp2 = float(matriz[y2] [x2])
        yp2 = float(matriz[y2] [x2 + 1])
        distancia = math.sqrt(((xp1 - xp2)**2)+((yp1 - yp2)**2))
        array[linha][coluna]=distancia
        linha = linha + 1
        y2 = y2 + 1
    else:   
        y2 = 6
        y1 = y1 + 1
        linha = 0
        coluna = coluna + 1

print(array)